development:
  clients:
    default:
      uri: mongodb+srv://francisco080304:U2aPykNCEpQtFz3c@socialconnect.rr4av.mongodb.net/social_connect_development?retryWrites=true&w=majority&appName=SocialConnect
      options:
        server_selection_timeout: 5
